### ISSUE TITLE
Free node->text before overwriting it?

### ISSUE THREAD

**Issue by IgorJorobus** [matthieu-labas/sxmlc#11]
Hello Matthieu, I'm not sure if this is actually an issue. 

 I've observed that when you're trying to replace the text on an XMLNode, you don't free previously allocated memory (by sx_strdup()). Is this a correct behaviour?

![image](https://user-images.githubusercontent.com/1852056/52535263-db24a900-2d2a-11e9-866d-ca4b1e3a38bb.png)

 Best regards, D.

**Comment by matthieu-labas** [comment]
Hi Damián,

That's a good catch! In the original version, sxmlc was assuming all strings were externally allocated, meaning the `free()` was supposed to be called by the entity responsible for providing it.

Some versions ago, that behaviour was changed to use `sx_strdup()` because sxmlc modifies the buffer while parsing it (putting some nul characters on separators to ease counting, before reverting it); so we could give `const char*` pointing to memory that was *physically read-only*.

I might have missed some calls to `free()` since then. I'll change that.

Best regards,
Matthieu

**Comment by IgorJorobus** [comment]
That's great Matthieu. Is good to see this library improving everyday.

**Comment by matthieu-labas** [comment]
I checked other text data (attribute names and values) and they were already freed before assignment. That was indeed a bug. Thanks again for the report!
