### ISSUE TITLE
Tag by Tag

### ISSUE THREAD

**Issue by embbo** [matthieu-labas/sxmlc#19]
Hi, I am using sxmlc Parsor which is really good for my Micro controller,  but my question is it possible if I can parsor tag by tag instead of whole xml. beacuse my micro controller ihave low memory .. 

for example .
Ist it just copy  these Tags 
`<UAObject NodeId="i=20002" BrowseName="0:Control" ParentNodeId="i=85">
.....
......
....
  </UAObject>`

than next tags 

<UAVariable NodeId="i=20003" BrowseName="0:FeedRate" ParentNodeId="i=20002">
...
...
...

  </UAVariable>

**Comment by matthieu-labas** [comment]
You'll probably want to use the SAX part instead of DOM: you provide callbacks that will be called whenever a new "XML event" occurs. See the `SAX_Callbacks` struct in `sxmlc.h` and the [HOWTO](http://sxmlc.sourceforge.net/howto.html).

If the structure of the string you want to parse is fixed and a "single node" (e.g. `<node attr="val" attr2="val2" />`) you can use the `XML_parse_1string(str, &node)` to parse its definition into `node`. But if it has text (e.g. `<node attr="val" attr2="val2">some text</node>`) then you can use `XMLDoc_parse_buffer_SAX()` providing a set of callbacks.

**Comment by embbo** [comment]
i have multiple tags 
<node attr="val1" attr2="val1" />)
<node attr="val2" attr2="val2" />)
<node attr="val3" attr2="val3" />)
I don't want to read whole data at once because I am using micro-controller
I just want tp  read and parse 1 by 1
