### ISSUE TITLE
simple xpath not working?

### ISSUE THREAD

**Issue by djcouchycouch** [matthieu-labas/sxmlc#3]
Hello!

I've been trying out sxmlc and I'm encountering problems with using the xpath support. It could very well be that I'm just using it wrong! :)

I've got a simple xml file and I want to get at an element that I know where it is.

    <?xml blah blah blah?>
    <video>
       <mode>1</mode>
    </video>

I want to get at the text in the <mode> node. I'm trying XMLSearch_init_from_XPath() but I can't seem to find the correct format for the xpath text.  I've tried "video/mode" and "/video/mode" but while the result returns 1 the contents of the nodes in the search have no text. Even if I put in a garbage path "adfladkfj" it still returns 1. 

So, how to do I format the xpath string so that I can directly get the <mode> node? 

Thanks!

**Comment by matthieu-labas** [comment]
(I have updated your comment to better show the XML to parse).

Which function are you using to parse the file? Since v4.1 there is an additionnal `XMLDoc_parse_*_DOM_text_as_nodes` that parses node text as children nodes, whose `text` attribute contains the text. When using `XMLDoc_parse_*_DOM` (e.g. `XMLDoc_parse_buffer_DOM`) you'll haveall text is concatenated in the `text` attribute. The `*_text_as_nodes` function show the problem you're experiencing but not the previous ones.

The following code works fine:

	XMLDoc doc;
	XMLSearch search;
	XMLNode* res;

	XMLDoc_init(&doc);
	XMLDoc_parse_buffer_DOM(C2SX("<?xml blah blah blah?><video><mode>1</mode></video>"), C2SX("simple"), &doc, 1);

	XMLSearch_init_from_XPath("/video/mode", &search);
	res = XMLSearch_next(doc.nodes[doc.i_root], &search);
	if (res != NULL)
		fprintf(stdout, "<%s>%s</%s>\n", res->tag, res->text == NULL ? "null" : res->text, res->tag);

	XMLSearch_free(&search, 0);
	XMLDoc_free(&doc);

Please feel free to reopen the bug if it's not working for you.

**Comment by djcouchycouch** [comment]
Thanks! It’s working now.

I just wasn’t using it correctly. :)
